#pragma once
#include <drivers/vga/vga.hpp>
#include <stdint.hpp>
#include <string.hpp>
#include <idt/idt.hpp>
#include <io/io.hpp>
#include <shell.hpp>
#include <paging/paging.hpp>
#include <fs/ramfs.hpp>